Feature/register&login
CryptoWorold/CryptoNews pull request #14
Opened 2024-06-10 09:25 UTC by RosenRoydev

Axios added in the project, Use state added of Login.jsx and Register.css is modified and works without scroll

2024-06-11 15:55 UTC, ZdravkoBorisov requested changes

2024-06-11 15:55 UTC, ZdravkoBorisov commented on CryptoWorld.News/cryptoworld.news.client/src/Pages/Login.jsx
> +    console.log(values);
Please remove the console.log()

2024-06-11 15:59 UTC, ZdravkoBorisov commented
There is an error in the browser console - No routes matched location "/Contact". Please review the Navbar.jsx

2024-06-14 08:36 UTC, RosenRoydev commented on CryptoWorld.News/cryptoworld.news.client/src/Pages/Login.jsx
> +    console.log(values);
done

2024-06-19 08:09 UTC, VelinArbov approved these changes

2024-06-19 08:10 UTC, ZdravkoBorisov approved these changes

2024-06-19 08:57 UTC, merged