Feature/register login validation
CryptoWorold/CryptoNews pull request #15
Opened 2024-06-12 08:06 UTC by Laracrofttx

2024-06-12 17:03 UTC, ZdravkoBorisov requested changes

2024-06-12 17:03 UTC, ZdravkoBorisov commented on CryptoWorld.News/CryptoWorld.News.Core/Services/AccountService.cs
> +				throw new ArgumentException("User with such email already exists.");
Please add error handling for these Exceptions.

2024-06-12 17:03 UTC, ZdravkoBorisov commented on CryptoWorld.News/CryptoWorld.News.Core/Services/AccountService.cs
> +
Please remove extra line

2024-06-12 17:03 UTC, ZdravkoBorisov commented on CryptoWorld.News/CryptoWorld.News.Core/Services/AccountService.cs
> +
Please remove extra line

2024-06-12 17:03 UTC, ZdravkoBorisov commented on CryptoWorld.News/CryptoWorld.News.Core/Services/AccountService.cs
>  }
Please add new line

2024-06-14 19:19 UTC, Laracrofttx commented on CryptoWorld.News/CryptoWorld.News.Core/Services/AccountService.cs
> +				throw new ArgumentException("User with such email already exists.");
Done

2024-06-14 19:19 UTC, Laracrofttx commented on CryptoWorld.News/CryptoWorld.News.Core/Services/AccountService.cs
> +
Done

2024-06-14 19:19 UTC, Laracrofttx commented on CryptoWorld.News/CryptoWorld.News.Core/Services/AccountService.cs
> +
Done

2024-06-14 19:19 UTC, Laracrofttx commented on CryptoWorld.News/CryptoWorld.News.Core/Services/AccountService.cs
>  }
Done

2024-06-19 08:08 UTC, VelinArbov approved these changes

2024-06-19 08:10 UTC, ZdravkoBorisov approved these changes

2024-06-19 08:18 UTC, merged