Feature/backend profile
CryptoWorold/CryptoNews pull request #21
Opened 2024-07-09 20:59 UTC by APeev89

Create logig for change password and change email

2024-07-10 15:36 UTC, ZdravkoBorisov requested changes

2024-07-10 15:36 UTC, ZdravkoBorisov commented on CryptoWorld.News/CryptoWorld.News.Server/appsettings.json
> +
Please exclude this from appsettings.json

2024-07-10 15:36 UTC, ZdravkoBorisov commented on CryptoWorld.News/cryptoworld.news.client/src/Components/Navbar.jsx
> +
Please remove extra line

2024-07-10 15:36 UTC, ZdravkoBorisov commented on CryptoWorld.News/cryptoworld.news.client/src/App.jsx
> +
Please remove extra line

2024-07-10 15:36 UTC, ZdravkoBorisov commented on CryptoWorld.News/CryptoWorld.News.Core/Services/UserProfileService.cs
> +            user.FirstName = model.FirstName;
Please add model validation. For example string.Empty or whitespace etc.

2024-07-10 15:36 UTC, ZdravkoBorisov commented on CryptoWorld.News/CryptoWorld.News.Core/Services/AccountService.cs
> +            this.secretKey = config["JWT:secretKey"];
Get the JWT key from correct source

2024-07-12 13:11 UTC, VelinArbov requested changes

2024-07-12 13:11 UTC, VelinArbov commented on CryptoWorld.News/CryptoWorld.News.Core/Services/AccountService.cs
> +                UserManager<ApplicationUser> _userManager,
In the constructor they should be without _ conventions is _ for private fields in our case should be private string _secretKey. Please fix it in all files.

2024-07-12 13:11 UTC, VelinArbov commented on CryptoWorld.News/CryptoWorld.News.Core/Services/AccountService.cs
> +            var key = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(this.secretKey));
here should be _secretKey

2024-07-12 13:11 UTC, VelinArbov commented on CryptoWorld.News/CryptoWorld.News.Core/ViewModels/ChangeEmailModel.cs
> +
empty space

2024-07-12 13:11 UTC, VelinArbov commented on CryptoWorld.News/CryptoWorld.News.Server/Controllers/UserProfileController.cs
> +
empty row

2024-07-16 07:15 UTC, VelinArbov requested changes

2024-07-16 07:15 UTC, VelinArbov commented on CryptoWorld.News/CryptoWorld.News.Server/Controllers/UserProfileController.cs
> +        public UserProfileController(IUserProfileService _profileService, ApplicationDbContext _context, UserManager<ApplicationUser> _userManager)
private field should be with _ like ---->   private readonly UserManager<ApplicationUser> _userManager; not in the constructer. Please fix whole PR

2024-07-16 07:16 UTC, VelinArbov commented on CryptoWorld.News/CryptoWorld.News.Server/Controllers/UserProfileController.cs
> +        public UserProfileController(IUserProfileService _profileService, ApplicationDbContext _context, UserManager<ApplicationUser> _userManager)
I mean every private fields

2024-07-17 12:59 UTC, ZdravkoBorisov approved these changes

2024-07-29 21:12 UTC, merged