Feature/Homepage-Frontend
CryptoWorold/CryptoNews pull request #22
Opened 2024-07-11 22:47 UTC by Laracrofttx

2024-07-12 13:12 UTC, VelinArbov requested changes

2024-07-12 13:12 UTC, VelinArbov commented on CryptoWorld.News/CryptoWorld.News.Core/Interfaces/INewsService.cs
> +        public Task<List<FilterNewsModel>> GetAllNewsFromTheLastTwentyDays();
This methods are the same please merge them into one generic method

2024-07-12 13:12 UTC, VelinArbov commented on CryptoWorld.News/CryptoWorld.News.Core/Services/News/NewsService.cs
> +            var daysAgo = DateTime.Now.AddDays(-7);
Merge this 2 methods in one

2024-07-21 21:03 UTC, Laracrofttx commented on CryptoWorld.News/CryptoWorld.News.Core/Services/News/NewsService.cs
> +            var daysAgo = DateTime.Now.AddDays(-7);
Done

2024-07-21 21:03 UTC, Laracrofttx commented on CryptoWorld.News/CryptoWorld.News.Core/Interfaces/INewsService.cs
> +        public Task<List<FilterNewsModel>> GetAllNewsFromTheLastTwentyDays();
Done

2024-07-23 18:52 UTC, merged