Feature/filter news backend
CryptoWorold/CryptoNews pull request #25
Opened 2024-07-15 07:43 UTC by HristinaGlavcheva

2024-07-15 15:20 UTC, ZdravkoBorisov requested changes

2024-07-15 15:20 UTC, ZdravkoBorisov commented on CryptoWorld.News/CryptoWorld.News.Core/Enumerations/NewsSorting.cs
> +        Soonest = 1,
Please rename this to Latest

2024-07-15 15:20 UTC, ZdravkoBorisov commented on CryptoWorld.News/CryptoWorld.News.Core/Enumerations/NewsSorting.cs
> +    }
Please add more filters.  For example filter news by specific dates, such as past week, past month, or a custom date range. Provide options to filter news based on geographical regions or countries - region Europe, Asia, etc

2024-07-16 21:29 UTC, HristinaGlavcheva commented on CryptoWorld.News/CryptoWorld.News.Core/Enumerations/NewsSorting.cs
> +        Soonest = 1,
Done

2024-07-16 21:29 UTC, HristinaGlavcheva commented on CryptoWorld.News/CryptoWorld.News.Core/Enumerations/NewsSorting.cs
> +    }
Done

2024-07-17 09:38 UTC, VelinArbov approved these changes

2024-07-17 10:40 UTC, ZdravkoBorisov approved these changes

2024-07-17 10:40 UTC, merged